# Generated by Django 5.0.3 on 2024-05-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='autoclick_power',
            field=models.IntegerField(default=0),
        ),
    ]
