# Generated by Django 4.2.6 on 2024-06-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_boost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='autoclick_price',
            field=models.IntegerField(default=3000),
        ),
    ]
