# Generated by Django 5.0.3 on 2024-06-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_core_autoclick_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Эффективный препарат', max_length=50)),
                ('number', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=False)),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.core')),
            ],
        ),
    ]
