# Generated by Django 5.0.3 on 2024-06-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_autoboost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoboost',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='core',
            name='autoclick_price',
        ),
    ]
